// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDuEG-E1ayEwNFDpccoqd7m0IVDfeNYsJ8',
    appId: '1:637957817781:web:05c166067de24bcb6245fc',
    messagingSenderId: '637957817781',
    projectId: 'beezafe-prb1',
    authDomain: 'beezafe-prb1.firebaseapp.com',
    storageBucket: 'beezafe-prb1.appspot.com',
    measurementId: 'G-LCXQDBTNHC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAeM-XF9CAWKivfnacsw2hyurhPUUNOp44',
    appId: '1:637957817781:android:aba0f12c33ef95ac6245fc',
    messagingSenderId: '637957817781',
    projectId: 'beezafe-prb1',
    storageBucket: 'beezafe-prb1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1GgzAkbe5nnX04JSDEc-QK97FnYbbdPk',
    appId: '1:637957817781:ios:7df91bf17b48595e6245fc',
    messagingSenderId: '637957817781',
    projectId: 'beezafe-prb1',
    storageBucket: 'beezafe-prb1.appspot.com',
    iosBundleId: 'mx.com.BeeZafe.beezafeMvl',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1GgzAkbe5nnX04JSDEc-QK97FnYbbdPk',
    appId: '1:637957817781:ios:7df91bf17b48595e6245fc',
    messagingSenderId: '637957817781',
    projectId: 'beezafe-prb1',
    storageBucket: 'beezafe-prb1.appspot.com',
    iosBundleId: 'mx.com.BeeZafe.beezafeMvl',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDuEG-E1ayEwNFDpccoqd7m0IVDfeNYsJ8',
    appId: '1:637957817781:web:c3ad697a24bac3056245fc',
    messagingSenderId: '637957817781',
    projectId: 'beezafe-prb1',
    authDomain: 'beezafe-prb1.firebaseapp.com',
    storageBucket: 'beezafe-prb1.appspot.com',
    measurementId: 'G-4SS682WJ1P',
  );

}